### PR TITLE
Pull request for first mile stone

### PR DESCRIPTION
**Pull request by uchennaanya**
These and more are the few things I did
I created the project with a description
Created the lib and bin folder
Created the main.rb file that displayed Hello world!
Made the main,rb file the executable file

### CODE REVIEW

**Review by ioilmio — CHANGES_REQUESTED** [review]
## Hello @uchennaanya 
### Changes requested: 
Please add the linters config files and ask for another rreview
Please be more descriptive with your commit messages and your PR

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle: 
Hello team. I've checked your repo and still can't find a .github folder. 
I'm giving the [link ](https://github.com/microverseinc/linters-config/)in here so you can follow the steps and arrange your linters.

Please fix this issue and submit for a re-review. :100: 
If you have a question about the review, feel free to reach me via Slack.
Eyüp Sercan UYGUR

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Required :recycle: 
Hello team,
Your Github action is not checking for any lint error.
One way to fix this is to manually trigger/activate it in the actions tab in the repository and then make some changes to your project and commit again.
Once you are done please request another review.
slack(@ebeagusamuel)

**Review by layzrd — APPROVED** [review]
### Status: Approved 🙌 🎇
Hi @uchennaanya , Congratulations 🎊 👏👏👏, you did very well on this project.  

Now, you can move ahead.

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/)

**Pull request merged**
